### ISSUE TITLE
BUG: Hardcoded paths in some files

### ISSUE THREAD

**Issue by HaoZeke** [d-SEAMS/pyseams#1]
https://github.com/d-SEAMS/pyseams/blob/aa099de13701b45c328d7a3dc085b62825617875/pyb11_srcs/py_one.cc#L7-L14

These will make it very unlikely to compile on another machine, @RuhiRG.

**Comment by RuhiRG** [comment]
Fixed in https://github.com/d-SEAMS/pyseams/commit/02d6132fba5518f26810a68057d946f68af85cd1
